# -*- coding: utf-8 -*-
"""UnZip.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eNhW0qwBt9z5nRr1lw6H3I-xoWUY0Llu
"""

#from google.colab import drive
#drive.mount('/content/drive')

import zipfile
path_to_zip_file = 'detr_training/coco_version_drone.zip'
directory_to_extract_to = 'detr_training/'
with zipfile.ZipFile(path_to_zip_file, 'r') as zip_ref:
    zip_ref.extractall(directory_to_extract_to)

